<!<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <?php $this->assets->outputJs(); ?>
    <title>Document</title>
</head>
<body>
<div id="two-way-binding">
    <textarea>{{ message }}</textarea>
</div>
<div id="re">
info:
</div>
</body>
</html>
<script>
    let code = 1;
    dd.runtime.permission.requestAuthCode({
        corpId: "ding6b2f4d380e29440d35c2f4657eb6378f",
        onSuccess : function(res) {
            // 调用成功时回调
            console.log(res)
            document.getElementById('re').innerHTML = res;
        },
        onFail : function(err) {
            // 调用失败时回调
            document.getElementById('re').innerHTML = err;
            console.log(err)
        }
    });

    const TwoWayBinding = {
        data() {
            return {
                message: code
            }
        }
    }

    Vue.createApp(TwoWayBinding).mount('#two-way-binding')
</script>