<!<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <?php $this->assets->outputJs(); ?>
    <title>Document</title>
</head>
<body>

</body>
</html>
<script>
    dd.runtime.permission.requestAuthCode({
        corpId: "<?php echo $id; ?>",
        onSuccess: function (request) {
            console.log(request)
        },
        onError: function (err) {
            console.log(err)
        }
    })
</script>